spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jinqiang
    password: jinqiang
    url: jdbc:mysql//192.168.31.194/simple-shop
    type: com.zaxxer.hikari.HikariDataSource